/* Shared data: icons, translations, and localized content. */

const icon = {
  heart: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.6l-1-1a5.5 5.5 0 1 0-7.8 7.8l1 1L12 21l7.8-7.6 1-1a5.5 5.5 0 0 0 0-7.8Z"/></svg>',
  coin: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><ellipse cx="12" cy="5" rx="7" ry="3"/><path d="M5 5v6c0 1.7 3.1 3 7 3s7-1.3 7-3V5"/><path d="M5 11v6c0 1.7 3.1 3 7 3s7-1.3 7-3v-6"/></svg>',
  work: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M10 6V5a2 2 0 0 1 2-2h0a2 2 0 0 1 2 2v1"/><rect x="3" y="6" width="18" height="14" rx="2"/><path d="M3 12h18"/></svg>',
  plane: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M22 2 11 13"/><path d="m22 2-7 20-4-9-9-4 20-7Z"/></svg>',
  book: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"/><path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2Z"/></svg>',
  gift: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="3" y="8" width="18" height="13" rx="2"/><path d="M12 8v13M3 12h18"/><path d="M7.5 8A2.5 2.5 0 1 1 12 6.5V8"/><path d="M16.5 8A2.5 2.5 0 1 0 12 6.5V8"/></svg>',
  bot: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="4" y="7" width="16" height="12" rx="3"/><path d="M12 7V4"/><circle cx="9" cy="13" r="1"/><circle cx="15" cy="13" r="1"/><path d="M9 17h6"/></svg>',
  stars: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="m12 3 1.7 4.8L19 9.5l-5.3 1.7L12 16l-1.7-4.8L5 9.5l5.3-1.7L12 3Z"/><path d="m19 15 .8 2.2L22 18l-2.2.8L19 21l-.8-2.2L16 18l2.2-.8L19 15Z"/></svg>'
};

const translations = {
  th: {
    brand: 'MuuPrachuap',
    tagline: 'มูครบ จบในแอปเดียว',
    greeting: 'สวัสดี,<br>ผู้มีศรัทธา 🙏',
    heroTitle: 'ชุดบูชาพร้อมส่ง ถึงโรงแรมหรือวัด',
    heroCopy: 'เลือกสถานที่แก้บนในประจวบ รับคำแนะนำชุดบูชา และแปลวิธีไหว้ให้พร้อม',
    heroButton: 'เริ่มเลย',
    searchPlaceholder: 'ค้นหาวัด ศาล หรือชุดบูชา',
    categoryTitle: 'เลือกตามเรื่องที่ตั้งใจ',
    seeAll: 'ดูทั้งหมด',
    placesTitle: 'สถานที่แนะนำยอดนิยม',
    nearby: 'ใกล้ฉัน',
    home: 'หน้าแรก',
    placesTab: 'สถานที่',
    setsTab: 'ชุดของ',
    cartTab: 'ตะกร้า',
    shopTitle: 'แนะนำชุดบูชา',
    addToCart: 'หยิบใส่ตะกร้า',
    orderTitle: 'สั่งซื้อ',
    deliveryTitle: 'จัดส่งไปที่',
    deliveryCopy: 'โรงแรม / วัด / จุดนัดรับในหัวหินและเมืองประจวบ',
    deliveryFee: 'ค่าจัดส่ง',
    total: 'รวมทั้งหมด',
    checkout: 'ดำเนินการชำระเงิน',
    languageTitle: 'ภาษา',
    userTitle: 'ผู้ใช้',
    userGreeting: 'ข้อมูลการใช้งานและทางลัดของคุณ',
    languageShortcut: 'เลือกภาษา',
    openCartShortcut: 'ดูตะกร้า',
    selectedLanguageLabel: 'ภาษาปัจจุบัน',
    deliveryName: 'ชื่อผู้รับ',
    deliveryPlace: 'สถานที่จัดส่ง',
    orderNote: 'หมายเหตุ',
    confirmOrder: 'ยืนยันคำสั่งซื้อจำลอง',
    recommendSet: 'ดูชุดที่แนะนำ',
    emptyCart: 'ยังไม่มีสินค้า',
    noResults: 'ไม่พบรายการที่ตรงกับคำค้น',
    orderReady: 'บันทึกคำสั่งซื้อจำลองแล้ว'
  },
  zh: {
    brand: 'MuuPrachuap',
    tagline: '一站式还愿与供品服务',
    greeting: '你好,<br>愿望清晰 福气常在 🙏',
    heroTitle: '供品可送至酒店或寺庙',
    heroCopy: '选择巴蜀府还愿地点，获得供品推荐与参拜翻译',
    heroButton: '开始',
    searchPlaceholder: '搜索寺庙、神坛或供品',
    categoryTitle: '按心愿选择',
    seeAll: '查看全部',
    placesTitle: '热门推荐地点',
    nearby: '附近',
    home: '首页',
    placesTab: '地点',
    setsTab: '供品',
    cartTab: '购物车',
    shopTitle: '推荐供品套装',
    addToCart: '加入购物车',
    orderTitle: '订单',
    deliveryTitle: '送达地点',
    deliveryCopy: '酒店 / 寺庙 / 华欣与巴蜀市区取货点',
    deliveryFee: '配送费',
    total: '合计',
    checkout: '继续付款',
    languageTitle: '语言',
    userTitle: '用户',
    userGreeting: '你的使用信息与快捷入口',
    languageShortcut: '选择语言',
    openCartShortcut: '查看购物车',
    selectedLanguageLabel: '当前语言',
    deliveryName: '收件人姓名',
    deliveryPlace: '配送地点',
    orderNote: '备注',
    confirmOrder: '确认模拟订单',
    recommendSet: '查看推荐供品',
    emptyCart: '购物车为空',
    noResults: '没有找到匹配结果',
    orderReady: '模拟订单已保存'
  },
  vi: {
    brand: 'MuuPrachuap',
    tagline: 'Đủ lễ, đủ nơi, trong một ứng dụng',
    greeting: 'Xin chào,<br>ước nguyện an lành 🙏',
    heroTitle: 'Bộ lễ giao đến khách sạn hoặc chùa',
    heroCopy: 'Chọn điểm trả lễ ở Prachuap, nhận gợi ý bộ lễ và bản dịch cách khấn',
    heroButton: 'Bắt đầu',
    searchPlaceholder: 'Tìm chùa, đền hoặc bộ lễ',
    categoryTitle: 'Chọn theo điều mong cầu',
    seeAll: 'Xem tất cả',
    placesTitle: 'Địa điểm phổ biến',
    nearby: 'Gần tôi',
    home: 'Trang chủ',
    placesTab: 'Địa điểm',
    setsTab: 'Bộ lễ',
    cartTab: 'Giỏ hàng',
    shopTitle: 'Bộ lễ gợi ý',
    addToCart: 'Thêm vào giỏ',
    orderTitle: 'Đặt hàng',
    deliveryTitle: 'Giao đến',
    deliveryCopy: 'Khách sạn / chùa / điểm nhận tại Hua Hin và Prachuap',
    deliveryFee: 'Phí giao',
    total: 'Tổng cộng',
    checkout: 'Thanh toán',
    languageTitle: 'Ngôn ngữ',
    userTitle: 'Người dùng',
    userGreeting: 'Thông tin sử dụng và lối tắt của bạn',
    languageShortcut: 'Chọn ngôn ngữ',
    openCartShortcut: 'Xem giỏ hàng',
    selectedLanguageLabel: 'Ngôn ngữ hiện tại',
    deliveryName: 'Tên người nhận',
    deliveryPlace: 'Nơi giao',
    orderNote: 'Ghi chú',
    confirmOrder: 'Xác nhận đơn mẫu',
    recommendSet: 'Xem bộ lễ gợi ý',
    emptyCart: 'Chưa có món nào',
    noResults: 'Không tìm thấy kết quả phù hợp',
    orderReady: 'Đã lưu đơn hàng mẫu'
  },
  en: {
    brand: 'MuuPrachuap',
    tagline: 'Offerings, vows, and local guidance in one app',
    greeting: 'Hello,<br>may your wish arrive gently 🙏',
    heroTitle: 'Offering sets delivered to hotels or temples',
    heroCopy: 'Pick a vow-fulfillment place in Prachuap, get a matching set, and translate worship steps',
    heroButton: 'Start',
    searchPlaceholder: 'Search temples, shrines, or offering sets',
    categoryTitle: 'Choose by intention',
    seeAll: 'View all',
    placesTitle: 'Popular recommended places',
    nearby: 'Nearby',
    home: 'Home',
    placesTab: 'Places',
    setsTab: 'Sets',
    cartTab: 'Cart',
    shopTitle: 'Recommended offering sets',
    addToCart: 'Add to basket',
    orderTitle: 'Order',
    deliveryTitle: 'Deliver to',
    deliveryCopy: 'Hotel / temple / pickup point in Hua Hin and Prachuap town',
    deliveryFee: 'Delivery fee',
    total: 'Total',
    checkout: 'Continue to payment',
    languageTitle: 'Language',
    userTitle: 'User',
    userGreeting: 'Your usage info and quick actions',
    languageShortcut: 'Choose language',
    openCartShortcut: 'Open basket',
    selectedLanguageLabel: 'Current language',
    deliveryName: 'Recipient name',
    deliveryPlace: 'Delivery place',
    orderNote: 'Note',
    confirmOrder: 'Confirm prototype order',
    recommendSet: 'View recommended set',
    emptyCart: 'Basket is empty',
    noResults: 'No matching results',
    orderReady: 'Prototype order saved'
  }
};

const content = {
  th: {
    categories: [
      ['การงาน', icon.work], ['การเงิน', icon.coin], ['ความรัก', icon.heart], ['โชคลาภ', icon.stars], ['เดินทาง', icon.plane],
      ['สุขภาพ', icon.gift], ['แก้บน', icon.book], ['ครอบครัว', icon.heart], ['ค้าขาย', icon.coin], ['ต่างชาติ', icon.plane]
    ],
    places: [
      ['พระอุปคุต', 'เมืองประจวบคีรีขันธ์', '4.9', '1.8 กม.', 'เด่นเรื่องโชคลาภ เงินทอง ค้าขาย และการเดินทาง แนะนำชุดมหาเฮงหรือเสริมทรัพย์', 1],
      ['ศาลหลักเมือง', 'เมืองประจวบคีรีขันธ์', '4.8', '3.2 กม.', 'ขอพรเรื่องงาน ความมั่นคง เริ่มต้นสิ่งใหม่ และคุ้มครองครอบครัว', 0],
      ['วัดห้วยมงคล', 'หัวหิน, ประจวบคีรีขันธ์', '4.9', '32 กม.', 'หลวงพ่อทวดองค์ใหญ่ เหมาะกับขอพรคุ้มครอง เดินทาง และโชคลาภ', 1],
      ['วัดอ่าวน้อย', 'อ่าวน้อย, เมืองประจวบ', '4.8', '18 กม.', 'วัดริมทะเล บรรยากาศสงบ เหมาะกับขอพรครอบครัว สุขภาพ และแก้บน', 2],
      ['ศาลเจ้าแม่นมสาว', 'สามร้อยยอด, ประจวบคีรีขันธ์', '4.8', '45 กม.', 'ศาลเจ้าศักดิ์สิทธิ์ เหมาะกับขอพรด้านสุขภาพ ครอบครัว และสิ่งที่ปรารถนา', 0]
    ],
    sets: [
      ['ชุดเสริมดวง', 'ธูป 9 ดอก, เทียน 2 เล่ม, น้ำแดง 2 ขวด, น้ำแพ็ค 1 แพ็ค, ดอกไม้ 1 ชุด', 299, 'เหมาะสำหรับเริ่มต้นวันใหม่ สอบ งาน เดินทาง และขอให้สิ่งติดขัดราบรื่นขึ้น', ['ธูป 9 ดอก', 'เทียน 2 เล่ม', 'น้ำแดง 2 ขวด', 'น้ำดื่ม 1 แพ็ค', 'ดอกไม้ 1 ชุด', 'บทไหว้พร้อมแปล']],
      ['ชุดมหาเฮง', 'ธูป 16 ดอก, เทียน 4 เล่ม, น้ำแดง 4 ขวด, น้ำแพ็ค 2 แพ็ค, ผลไม้มงคล 5 อย่าง', 499, 'ชุดยอดนิยมสำหรับพระอุปคุตและสถานที่ขอโชคลาภ เน้นเฮง งานดี เงินเข้า และโอกาสใหม่', ['ธูป 16 ดอก', 'เทียน 4 เล่ม', 'น้ำแดง 4 ขวด', 'น้ำดื่ม 2 แพ็ค', 'ผลไม้มงคล 5 อย่าง', 'พวงมาลัยดาวเรือง']],
      ['ชุดเสริมทรัพย์', 'ธูป 9 ดอก, เทียนทอง 2 เล่ม, น้ำแดง 3 ขวด, น้ำแพ็ค 1 แพ็ค, ส้ม 9 ลูก', 399, 'เหมาะกับค้าขาย รายได้ งานใหม่ และแก้บนเรื่องเงินทองแบบเตรียมของไม่เยอะเกินไป', ['ธูป 9 ดอก', 'เทียนทอง 2 เล่ม', 'น้ำแดง 3 ขวด', 'น้ำดื่ม 1 แพ็ค', 'ส้ม 9 ลูก', 'มาลัยหรือดอกดาวเรือง']]
    ],
    detailCopy: 'เลือกชุดบูชาตามสถานที่และเรื่องที่ตั้งใจ แอปจะแสดงจำนวนธูป เทียน น้ำแดง น้ำแพ็ค และของประกอบให้เตรียมง่าย'
  },
  zh: {
    categories: [['事业', icon.work], ['财富', icon.coin], ['爱情', icon.heart], ['好运', icon.stars], ['旅行', icon.plane], ['健康', icon.gift], ['还愿', icon.book], ['家庭', icon.heart], ['生意', icon.coin], ['游客', icon.plane]],
    places: [['优婆掬尊者 考冲卡雀', '巴蜀市区', '4.9', '1.8 公里', '适合求财运、生意、旅行顺利，推荐好运套装或招财套装', 1], ['巴蜀府城市柱神庙', '巴蜀市区', '4.8', '3.2 公里', '适合祈求事业、稳定、新开始与家人平安', 0], ['怀蒙坤寺', '华欣, 巴蜀府', '4.9', '32 公里', '大型龙婆托佛像，适合祈求平安、旅行顺利与好运', 1], ['奥诺寺', '巴蜀市区海湾', '4.8', '18 公里', '宁静海边寺庙，适合为家庭、健康与还愿祈福', 2]],
    sets: [['转运套装', '香 9 支、蜡烛 2 支、红水 2 瓶、饮用水 1 箱、鲜花 1 组', 299, '适合求工作、考试、旅行与让事情更顺利。', ['香 9 支', '蜡烛 2 支', '红水 2 瓶', '饮用水 1 箱', '鲜花 1 组', '祈福词翻译']], ['好运大发套装', '香 16 支、蜡烛 4 支、红水 4 瓶、饮用水 2 箱、五种吉祥水果', 499, '适合优婆掬尊者与求财地点，重点是好运、工作机会与财富。', ['香 16 支', '蜡烛 4 支', '红水 4 瓶', '饮用水 2 箱', '五种吉祥水果', '万寿菊花环']], ['招财套装', '香 9 支、金烛 2 支、红水 3 瓶、饮用水 1 箱、橙子 9 个', 399, '适合生意、收入、新工作与简单还愿。', ['香 9 支', '金烛 2 支', '红水 3 瓶', '饮用水 1 箱', '橙子 9 个', '花环或万寿菊']]],
    detailCopy: '按地点与心愿选择供品，应用会显示香、蜡烛、红水、饮用水和其他供品数量。'
  },
  vi: {
    categories: [['Công việc', icon.work], ['Tài lộc', icon.coin], ['Tình duyên', icon.heart], ['May mắn', icon.stars], ['Du lịch', icon.plane], ['Sức khỏe', icon.gift], ['Trả lễ', icon.book], ['Gia đình', icon.heart], ['Kinh doanh', icon.coin], ['Du khách', icon.plane]],
    places: [['Phra Upakhut Khao Chong Krachok', 'Thành phố Prachuap', '4.9', '1.8 km', 'Nổi bật về tài lộc, buôn bán, đi lại; gợi ý bộ Maha Heng hoặc bộ tài lộc', 1], ['Đền Trụ Cột Thành Phố Prachuap', 'Thành phố Prachuap', '4.8', '3.2 km', 'Phù hợp cầu công việc, ổn định, khởi đầu mới và bình an gia đình', 0], ['Wat Huay Mongkol', 'Hua Hin, Prachuap', '4.9', '32 km', 'Tượng Luang Pu Thuat lớn, phù hợp cầu bình an, đi lại và may mắn', 1], ['Wat Ao Noi', 'Ao Noi, Prachuap', '4.8', '18 km', 'Chùa ven biển yên tĩnh, phù hợp cầu gia đình, sức khỏe và trả lễ', 2]],
    sets: [['Bộ tăng vận', '9 nén nhang, 2 cây nến, 2 chai nước đỏ, 1 lốc nước, 1 bộ hoa', 299, 'Phù hợp cầu công việc, thi cử, đi lại và mọi việc hanh thông hơn.', ['9 nén nhang', '2 cây nến', '2 chai nước đỏ', '1 lốc nước uống', '1 bộ hoa', 'Bản dịch lời khấn']], ['Bộ Maha Heng', '16 nén nhang, 4 cây nến, 4 chai nước đỏ, 2 lốc nước, 5 loại trái cây may mắn', 499, 'Phù hợp Phra Upakhut và điểm cầu tài lộc, nhấn mạnh may mắn, công việc và tiền vào.', ['16 nén nhang', '4 cây nến', '4 chai nước đỏ', '2 lốc nước uống', '5 loại trái cây may mắn', 'Vòng hoa cúc']], ['Bộ tài lộc', '9 nén nhang, 2 nến vàng, 3 chai nước đỏ, 1 lốc nước, 9 quả cam', 399, 'Phù hợp buôn bán, thu nhập, công việc mới và trả lễ đơn giản.', ['9 nén nhang', '2 nến vàng', '3 chai nước đỏ', '1 lốc nước uống', '9 quả cam', 'Vòng hoa hoặc hoa cúc']]],
    detailCopy: 'Chọn bộ lễ theo địa điểm và mong cầu; ứng dụng hiển thị số nhang, nến, nước đỏ, nước uống và lễ vật cần chuẩn bị.'
  },
  en: {
    categories: [['Career', icon.work], ['Money', icon.coin], ['Love', icon.heart], ['Luck', icon.stars], ['Travel', icon.plane], ['Health', icon.gift], ['Vows', icon.book], ['Family', icon.heart], ['Business', icon.coin], ['Visitors', icon.plane]],
    places: [['Phra Upakhut, Khao Chong Krachok', 'Prachuap town', '4.9', '1.8 km', 'Known for luck, money, trade, and travel blessings. Maha Heng or wealth sets are recommended', 1], ['Prachuap City Pillar Shrine', 'Prachuap town', '4.8', '3.2 km', 'Good for career, stability, fresh starts, and family protection', 0], ['Wat Huay Mongkol', 'Hua Hin, Prachuap', '4.9', '32 km', 'Known for the large Luang Pu Thuat statue, popular for safety, travel, and luck', 1], ['Wat Ao Noi', 'Ao Noi, Prachuap town', '4.8', '18 km', 'A calm seaside temple often chosen for family, health, and vow fulfillment', 2]],
    sets: [['Fortune boost set', '9 incense sticks, 2 candles, 2 red sodas, 1 water pack, 1 flower set', 299, 'Good for work, exams, travel, and clearing small obstacles before a new start.', ['9 incense sticks', '2 candles', '2 red sodas', '1 drinking-water pack', '1 flower set', 'Translated prayer']], ['Maha Heng set', '16 incense sticks, 4 candles, 4 red sodas, 2 water packs, 5 auspicious fruits', 499, 'Recommended for Phra Upakhut and luck-focused places. Built for fortune, work chances, and money flow.', ['16 incense sticks', '4 candles', '4 red sodas', '2 drinking-water packs', '5 auspicious fruits', 'Marigold garland']], ['Wealth set', '9 incense sticks, 2 gold candles, 3 red sodas, 1 water pack, 9 oranges', 399, 'Good for trade, income, new jobs, and simple money-related vow fulfillment.', ['9 incense sticks', '2 gold candles', '3 red sodas', '1 drinking-water pack', '9 oranges', 'Garland or marigolds']]],
    detailCopy: 'Choose a set by sacred place and intention. The app lists incense, candles, red soda, water packs, and other offering items clearly.'
  }
};

const languageOptions = [
  ['th', 'ไทย', 'th'],
  ['zh', '中文 简体', 'cn'],
  ['vi', 'Tiếng Việt', 'vn'],
  ['en', 'English', 'en']
];
